### ISSUE TITLE
Certification Checklist

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/askTheDM#66]
- [x] Test "Ask *invoke* to *do something* but leave task blank
     -tested Ask DM to ... she responds with "I'm sorry I currently Don't know that spell."
     -She needs to prompt for the missing info, such as "to do 'abc', say 'abc' "
     -when you respond to the prompt, the skill continues prompting until all needed info is collected, then provides a contextualized non-error response
- [x] invoke the skill when prompted to respond, say something that matches one of the intents, but with wrong slots used.
     -test "ask dm for what is the range of blind". Tested: "Im sorry I currently don't know 'blind' "
- [x] Add disclaimer for ages 13+
- [x] Add disclaimer for wizards of the coast
- [x] At least one example phrase has been provided on the skill in the skill store page
- [x] First phrase clearly indicates how to begin using the skill, and includes the wake word and invocation name
- [x] Example phrases containing the wake and invocation name must use a supported format for invoking a skill. 
   - Can't be "Alexa hack the pentagon, then also ask blah blah" they say not cool, i guess
- [x] Provide a short description as shown in the list of skills. Describe the skill's core functionality.
- [x] The invocation name uses title case. I'm assuming to distinguish that this is the invocation name
- [x] Test "Open invocation Name". 
- [x] Test a variety of intents
- [x] Review the skill title and icon, ensure they are relevant. 
- [x] Individual letters followed by a period for example TV should be expressed as "t. v.", same for OK, and compound words like "AccessHD = Access h. d."
- [x] Stopping: after hearing the prompt "ask dm what is fireball" .... "alexa stop" she stops. works
     - Need to test with just prompt of stop, and cancel, without saying Alexa in front as well.
- [x] phrases are easy and natural to say
- [x] Example phrases, can't contain emoticons, symbols, or grammar errors.
- [x] Verify that each example phrase is included as a sample utterance
- [x] According to the security requirement: we must host the webpage on our own endpoint
- [x] Open the detail card for the full description. Captures any prerequisites needed to use the skill, describes the core functionality
- [x] If the short or full description includes a URL, make sure the URL is connected
- [x] If we have privacy policy or terms of use links, have them open in a browser
- [x] Look into Home Cards: Graphical cards displayed in the Alexa app to describe or enhance the voice interaction
- [x] Test "Ask *Invocation Name* to *do something*"
    - tested Ask DM to tell me the range of fireball. works

- [x] Ask *invoke* for abc and skill ends. One-shot phrasing utterance
     - Tested "ask dm for range of fireball" works

- [x] Change invocation name to just "dm"

**Comment by jnoehren** [comment]
I am a little confused at the fourth one, we don't have a web page yet right or am I misunderstanding haha

**Comment by omegabytes** [comment]
just a rant, but one of the items of feedback was make sure the example request is in the app...and they all were
